name: mobilehigertech
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  provider: ^6.0.5

  cupertino_icons: ^1.0.8
  http: ^0.13.6  # Pastikan versinya terbaru

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  # Hanya satu kali

  assets:
    - assets/hgt.png
    - assets/higertech.png
